# Generated by Django 4.0.3 on 2022-06-03 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/services')),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('site_title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('suburb', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=50)),
                ('site_contact', models.CharField(max_length=50)),
                ('site_attribute', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('clean_schedule', models.CharField(max_length=100)),
                ('clean_area', models.CharField(max_length=50)),
                ('clean_task_enable', models.BooleanField()),
                ('startdate', models.DateField()),
                ('extra_detail', models.TextField()),
                ('cleaner', models.ManyToManyField(to='dnamservices.employee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnamservices.client')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder', models.CharField(max_length=50)),
                ('workorder_title', models.CharField(max_length=50)),
                ('pricing', models.IntegerField()),
                ('comments', models.CharField(max_length=50)),
                ('completed_by', models.CharField(max_length=50)),
                ('completion_date', models.DateTimeField()),
                ('extra_detail', models.TextField()),
                ('assigned_to', models.ManyToManyField(to='dnamservices.employee')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnamservices.client')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnamservices.sites')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.IntegerField()),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thrusday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('saturday', models.IntegerField()),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnamservices.sites')),
            ],
        ),
        migrations.CreateModel(
            name='Superviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder', models.CharField(max_length=50)),
                ('pricing', models.IntegerField()),
                ('comments', models.CharField(max_length=50)),
                ('completed_by', models.CharField(max_length=50)),
                ('completion_date', models.DateTimeField()),
                ('extra_detail', models.TextField()),
                ('assigned_to', models.ManyToManyField(to='dnamservices.employee')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnamservices.client')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnamservices.sites')),
            ],
        ),
    ]
