# Generated by Django 4.0.3 on 2022-06-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='cient_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='location',
            new_name='cient_location',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='cient_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='street',
            new_name='cient_street',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='website',
            new_name='cient_website',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='address',
            new_name='employee_address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='contact',
            new_name='employee_contact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='employee_email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='employee_user',
        ),
        migrations.RenameField(
            model_name='superviser',
            old_name='address',
            new_name='superviser_address',
        ),
        migrations.RenameField(
            model_name='superviser',
            old_name='contact',
            new_name='superviser_contact',
        ),
        migrations.RenameField(
            model_name='superviser',
            old_name='name',
            new_name='superviser_name',
        ),
        migrations.RenameField(
            model_name='superviser',
            old_name='user',
            new_name='superviser_user',
        ),
    ]
