# Generated by Django 4.0.3 on 2022-06-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0002_rename_email_client_cient_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cient_email',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cient_location',
            new_name='client_location',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cient_name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cient_street',
            new_name='client_street',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cient_website',
            new_name='client_website',
        ),
    ]
