# Generated by Django 4.0.3 on 2022-06-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0003_rename_cient_email_client_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='superviser',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
