# Generated by Django 4.0.3 on 2022-06-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0004_employee_superviser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='superviser',
            field=models.BooleanField(default=False),
        ),
    ]
