# Generated by Django 4.0.3 on 2022-06-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0006_complainttask_complaint_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_image', models.FileField(upload_to='Invoice_in')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_image', models.FileField(upload_to='Invoice_out')),
            ],
        ),
    ]
