# Generated by Django 4.0.3 on 2022-06-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0007_invoicein_invoiceout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertask',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
