# Generated by Django 4.0.3 on 2022-06-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0009_client_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='remove'),
        ),
    ]
