# Generated by Django 4.0.3 on 2022-06-05 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0010_alter_client_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttask',
            name='complaint_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnamservices.superviser'),
        ),
        migrations.AlterField(
            model_name='workordertask',
            name='workorder_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnamservices.superviser'),
        ),
    ]
