# Generated by Django 4.0.3 on 2022-06-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0013_alter_complainttask_complaint_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='friday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='monday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='saturday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sites',
            name='sunday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='thrusday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='tuesday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='wednesday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='clean_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='clean_schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='clean_task_enable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='cleaner',
            field=models.ManyToManyField(blank=True, null=True, to='dnamservices.employee'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='extra_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='postcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='site_attribute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='site_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='site_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='site_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='suburb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
