# Generated by Django 4.0.3 on 2022-06-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0014_sites_friday_sites_monday_sites_saturday_sites_save_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='save',
        ),
    ]
