# Generated by Django 4.0.3 on 2022-06-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0017_rename_save_sites_enter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='remove',
            field=models.BooleanField(default=False),
        ),
    ]
