# Generated by Django 4.0.3 on 2022-06-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0018_sites_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sites',
            name='enter',
            field=models.BooleanField(verbose_name='save'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='remove',
            field=models.BooleanField(default=False, verbose_name='delete'),
        ),
    ]
