# Generated by Django 4.0.3 on 2022-06-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0019_employee_delete_alter_sites_enter_alter_sites_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicein',
            name='delete',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceout',
            name='delete',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
