# Generated by Django 4.0.3 on 2022-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0021_invoicein_name_invoiceout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicein',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceout',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
