# Generated by Django 4.0.3 on 2022-06-06 15:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dnamservices', '0025_alter_invoicein_in_image_alter_invoiceout_out_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
